# Generated by Django 5.0.6 on 2024-05-30 16:15

import posts.SizeValidation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='posts/image/', validators=[posts.SizeValidation.file_size]),
        ),
    ]
