# Generated by Django 5.0.6 on 2024-05-29 19:32

import accounts.SizeValidation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='followings',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='posts',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profilepic/', validators=[accounts.SizeValidation.file_size]),
        ),
    ]
